site_name: TRaSH Guides
site_description: Guides mainly for Sonarr/Radarr/Bazarr and everything related to it.
site_author: TRaSH
site_url: https://trash-guides.info/

repo_url: https://github.com/TRaSH-Guides/Guides
repo_name: TRaSH-Guides

# ignores absolute warnings we have
# warns on missing/broken links
validation:
  omitted_files: warn
  not_found: warn
  absolute_links: ignore
# fails to build on warnings
strict: true

copyright: Copyright &copy; 2022 TRaSH

extra:
  analytics:
    provider: google
    property: G-ZZKM4MPQXL
  social:
    - icon: fontawesome/brands/discord
      link: https://trash-guides.info/discord
    - icon: fontawesome/brands/square-github
      link: https://github.com/TRaSH-Guides/Guides

extra_css:
  - stylesheets/extra.css
  - stylesheets/github-permalink-style.css

markdown_extensions:
  # extensions de la bibliothèque markdown standard
  - meta                          # Métadonnées
  - def_list                      # Listes de définition.
  - attr_list                     # Sélecteurs CSS et attributs HTML personnalisés
  - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
  - admonition                    # Pour permettre les admonitions de MkDocs # Boite d'avertissements  !!! info "ma remarque"
  - toc:                          # Configuration de la table des matières générée automatiquement à partir des titres du niveau 2
        permalink: "&lozf;"          # Ajoute un symbole lien hypertexte vers l'ancre du titre #le-titre 
        toc_depth: 4                # Limite de la profondeur d'inclusion des titres dans la table des matières
  - nl2br                         # Ajoute un retour à la ligne <br> après un saut de ligne simple # A activer pour admonition et si l'option "Sauts de ligne stricts" n'est pas activée dans les réglages de l'éditeur d'Obsidian
  - mdx_breakless_lists           # Permet de commencer une liste sans faire de saut de ligne en amont en ajoutant systématiquement un saut de ligne
  - sane_lists                    # Produit le même affichage de liste qu'Obsidian démarage au nombre indiqué au début d'une liste ordonné : https://python-markdown.github.io/extensions/sane_lists/ 
  - smarty                        # The SmartyPants extension converts ASCII dashes, quotes and ellipses to their HTML entity equivalents https://python-markdown.github.io/extensions/smarty/
  - tables                        # Pour les tableaux https://squidfunk.github.io/mkdocs-material/reference/data-tables/
  # extensions de python-markdown https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.details              # plier/déplier les avertissements - admonition collapsable
  - pymdownx.caret                # texte ^^souligné^^ ou en ^exposant^.
  - pymdownx.mark                 # texte ==surligné==.
  - pymdownx.tilde                # texte ~~barré~~ ou en ~indice~.
  - pymdownx.critic               # Pour du marquage et commentaires de révision de texte
  - pymdownx.magiclink            # Reconnait automatiquement un lien, une adresse à partir de son URL et bien plus : https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
  - pymdownx.highlight            # Coloration syntaxique du code
  - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
  - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    true    #   avec cases d'origine
        # clickable_checkbox: true    #   et cliquables.
  - pymdownx.superfences:    # Imbrication de blocs. # pour admonitions MkDocs
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
  - pymdownx.emoji:               # Émojis  :boom:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:          # Formules en LaTeX 
        generic: true
        smart_dollar: false 

plugins:
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - markdownextradata:
      data: docs/json
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: fr
          default: true
          name: Français
          build: true
        - locale: en
          name: English
          build: true
          theme:
            palette:
              # Palette toggle for light mode
              - media: "(prefers-color-scheme: light)"
                primary: red
                scheme: default
              # Palette toggle for dark mode
              - media: "(prefers-color-scheme: dark)"
                primary: pink
                scheme: slate
  - git-revision-date-localized:
      type: datetime
      locale: en
  #    fallback_to_build_date: false
  - awesome-pages
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
  - macros:
      j2_block_start_string: "[[%"
      j2_block_end_string: "%]]"
      j2_variable_start_string: "[["
      j2_variable_end_string: "]]"
  - redirects:
      redirect_maps:
        #updates.txt: updates.txt
        discord.md: https://discord.gg/4K2kdvwzFh
        syno-script.md: https://github.com/TRaSH-/Guides-Synology-Templates/blob/main/script/trash_syno_installer.sh
        # Radarr redirects
        Radarr/Radarr-setup-custom-formats.md: Radarr/radarr-setup-quality-profiles.md
        Radarr/radarr-setup-custom-formats-anime.md: Radarr/radarr-setup-quality-profiles-anime.md
        Radarr/radarr-setup-custom-formats-french.md: Radarr/radarr-setup-quality-profiles-french-en.md
        # Sonarr redirects
        Sonarr/sonarr-setup-custom-formats.md: Sonarr/sonarr-setup-quality-profiles.md
        Sonarr/sonarr-setup-custom-formats-anime.md: Sonarr/sonarr-setup-quality-profiles-anime.md
        # How to old redirects
        How-to-setup-for/index.md: Hardlinks/How-to-setup-for/index.md
        How-to-setup-for/Docker.md: Hardlinks/How-to-setup-for/Docker.md
        How-to-setup-for/Dockstarter.md: Hardlinks/How-to-setup-for/Dockstarter.md
        How-to-setup-for/Native.md: Hardlinks/How-to-setup-for/Native.md
        How-to-setup-for/Synology.md: Hardlinks/How-to-setup-for/Synology.md
        How-to-setup-for/Unraid.md: Hardlinks/How-to-setup-for/Unraid.md
        # Random redirects
        Misc/trash-sync.md: Guide-Sync/index.md
        # Shortcuts redirects
        hardlinks.md: Hardlinks/Hardlinks-and-Instant-Moves.md
        hardlink.md: Hardlinks/Hardlinks-and-Instant-Moves.md
        check-hardlinks.md: Hardlinks/Check-if-hardlinks-are-working.md
        custom-formats.md: Radarr/Radarr-collection-of-custom-formats.md
        cf.md: Radarr/Radarr-collection-of-custom-formats.md
        TorGuard.md: Misc/How-to-setup-Torguard-for-port-forwarding.md
        torguard.md: Misc/How-to-setup-Torguard-for-port-forwarding.md
        compose.md: Misc/how-to-provide-a-docker-compose.md
        Golden-Rule.md: Misc/x265-4k.md
        show-unknown.md: Radarr/Tips/Radarr-show-unknown-movie-items.md
        merge-quality.md: Radarr/Tips/Merge-quality.md
        jdupes.md: Hardlinks/Replace-copies-with-hardlinks.md
        # Recyclarr redirects
        Recyclarr/recyclarr-configs.md: https://recyclarr.dev/wiki/guide-configs/
        Recyclarr/recyclarr-configs-sqp.md: https://recyclarr.dev/wiki/sqp-configs/

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue
      scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: "Noto Sans"
    code: "Encode Sans Expanded"
  favicon: img/favicon.png
  logo: img/logo.png
